### ISSUE TITLE
Demo issues blocking repointing willow.cottagelabs.com to our newest demo machine

### ISSUE THREAD

**Issue by emanuil-tolev** [CottageLabs/willow#111]
- [ ] Background image and heading text are only on the old vagrant demo ( http://willow.cottagelabs.com ). Work to be carried out in #115 
- [ ] Thumbnails (e.g. for example object "Willow 5") do not seem to show up. This could be an export, import or any other problem (e.g. on every willow restart). Work carried out in #71 
- [ ] solr fails to reindex all of fedora's data. It crashes. Work carried out in #113 
- [ ] once those are fixed, repoint willow.cottagelabs.com to our newest demo machine and delete willow-dev.cottagelabs.com. Work to be carried out in #116 
- [ ] fix the "Share your work" and "Create work" buttons as they doesn't work on the new demo site. Work carried out in #114

**Comment by Nimphal** [comment]
I have created separate issues for each of the points. Closing as will be following them separately.
